// Package LifeService comment
// This file was generated by tars2go 1.1.4
// Generated from ServerStatus.tars
package LifeService

import (
	"fmt"

	"github.com/TarsCloud/TarsGo/tars/protocol/codec"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = fmt.Errorf
var _ = codec.FromInt8

type ErrorCode int32

const (
	ErrorCode_SUCCESS      = 0
	ErrorCode_USERNOTEXIST = 1
	ErrorCode_USEREXIST    = 2
	ErrorCode_PHONEEXIST   = 3
	ErrorCode_SERVERERROR  = 4
)
